version: '3'
volumes:
  mysql:
    driver:
      local
services:
  app:
    build: .
    volumes:
      - ./:/go
    working_dir: /go
    depends_on:
      - mysql
    environment:
      ENV: dev
      PORT: 8080
      DB_HOST: mysql
      DB_USER: todo
      DB_PASSWORD: 123
      DB_NAME: todo
    ports:
      - "8080:8080"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: todo
      MYSQL_USER: todo
      MYSQL_PASSWORD: 123
    volumes:
      - "./data/mysql:/docker-entrypoint-initdb.d"
      - "mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
